### PR TITLE
Added an input to specify the directory where flake8 should be run

### LINKED ISSUE #5: Run flake8 against a specific directory
Hi @julianwachholz 

thanks for maintaining this repo!

I'd like to know whether it is possible to run flake8 against a specific directory instead the whole repo (perhaps we can pass args)?

ie: I have a project where all my relevant python file reside in a directory called `./library/`, when I run this flake8-action it is run against the whole project, even though I've added this piece of code in my github action file:

```yaml
on:
  pull_request:
    paths:
      - 'library/*.py'
```

not really familiar with github workflow syntax, maybe I'm missing something? In any case any pointer would be appreciated. Thanks!

### PR DESCRIPTION
**Pull request by afonsoVale**
Resolves #5

### CODE REVIEW

**Comment by julianwachholz** [comment]
Hey thank you for this! I'll have a look at this asap.

**Comment by afonsoVale** [comment]
No problem! I also had a look at trying to get a workaround for the 50 API request limit, but that one isn't as simple. But the idea is that the annotations need to be sent in several chunks of 50 max.

**Comment by guits** [comment]
@afonsoVale @julianwachholz any news on this? :slightly_smiling_face: 

thanks!

**Comment by guits** [comment]
@afonsoVale thanks for this patch

**Comment by julianwachholz** [comment]
@guits sorry I haven't had the time yet. I will try to get this merged soon-ish 🙈

**Pull request closed without merging**
